# Generated by Django 2.2.7 on 2019-11-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questiontinder', '0005_auto_20191112_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(max_length=40),
        ),
    ]
