# Generated by Django 2.2.7 on 2019-11-13 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questiontinder', '0006_auto_20191113_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
